In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
df= pd.read_csv('PizzaTrain.csv')
df.head()

giver_username_if_known  number_of_downvotes_of_request_at_retrieval  \
0                     NaN                                            0   
1                     NaN                                            2   
2                     NaN                                            0   
3                     NaN                                            0   
4                     NaN                                            6   

   number_of_upvotes_of_request_at_retrieval post_was_edited request_id  \
0                                          1           false   t3_l25d7   
1                                          5           false   t3_rcb83   
2                                          3           false   t3_lpu5j   
3                                          1            true   t3_mxvj3   
4                                          6           false  t3_1i6486   

   request_number_of_comments_at_retrieval  \
0                                        0   
1                                        0   
2                                        0   
3                                        4   
4                                        5   

                                        request_text  \
0  Hi I am in need of food for my 4 children we a...   
1  I spent the last money I had on gas today. Im ...   
2  My girlfriend decided it would be a good idea ...   
3  It's cold, I'n hungry, and to be completely ho...   
4  hey guys:\r\n I love this sub. I think it's gr...   

                             request_text_edit_aware  \
0  Hi I am in need of food for my 4 children we a...   
1  I spent the last money I had on gas today. Im ...   
2  My girlfriend decided it would be a good idea ...   
3  It's cold, I'n hungry, and to be completely ho...   
4  hey guys:\r\n I love this sub. I think it's gr...   

                                       request_title  \
0            Request Colorado Springs Help Us Please   
1  [Request] California, No cash and I could use ...   
2  [Request] Hungry couple in Dundee, Scotland wo...   
3  [Request] In Canada (Ontario), just got home f...   
4  [Request] Old friend coming to visit. Would LO...   

   requester_account_age_in_days_at_request              ...                \
0                                  0.000000              ...                 
1                                501.111100              ...                 
2                                  0.000000              ...                 
3                                  6.518438              ...                 
4                                162.063252              ...                 

   requester_received_pizza  \
0                     False   
1                     False   
2                     False   
3                     False   
4                     False   

                     requester_subreddits_at_request  \
0                                                NaN   
1  AskReddit,Eve,IAmA,MontereyBay,RandomKindness,...   
2                                                NaN   
3            AskReddit,DJs,IAmA,Random_Acts_Of_Pizza   
4  GayBrosWeightLoss,RandomActsOfCookies,Random_A...   

   requester_upvotes_minus_downvotes_at_request  \
0                                             0   
1                                            34   
2                                             0   
3                                            54   
4                                          1121   

   requester_upvotes_minus_downvotes_at_retrieval  \
0                                               1   
1                                            4258   
2                                               3   
3                                              59   
4                                            1225   

   requester_upvotes_plus_downvotes_at_request  \
0                                            0   
1                                          116   
2                                            0   

In [7]:
drop_columns = ["giver_username_if_known", "post_was_edited","request_id","requester_username","unix_timestamp_of_request",
                "unix_timestamp_of_request_utc","request_text_edit_aware","requester_user_flair"]
df.drop(drop_columns,inplace=True,axis=1)

In [8]:
df.head()


number_of_downvotes_of_request_at_retrieval  \
0                                            0   
1                                            2   
2                                            0   
3                                            0   
4                                            6   

   number_of_upvotes_of_request_at_retrieval  \
0                                          1   
1                                          5   
2                                          3   
3                                          1   
4                                          6   

   request_number_of_comments_at_retrieval  \
0                                        0   
1                                        0   
2                                        0   
3                                        4   
4                                        5   

                                        request_text  \
0  Hi I am in need of food for my 4 children we a...   
1  I spent the last money I had on gas today. Im ...   
2  My girlfriend decided it would be a good idea ...   
3  It's cold, I'n hungry, and to be completely ho...   
4  hey guys:\r\n I love this sub. I think it's gr...   

                                       request_title  \
0            Request Colorado Springs Help Us Please   
1  [Request] California, No cash and I could use ...   
2  [Request] Hungry couple in Dundee, Scotland wo...   
3  [Request] In Canada (Ontario), just got home f...   
4  [Request] Old friend coming to visit. Would LO...   

   requester_account_age_in_days_at_request  \
0                                  0.000000   
1                                501.111100   
2                                  0.000000   
3                                  6.518438   
4                                162.063252   

   requester_account_age_in_days_at_retrieval  \
0                                  792.420405   
1                                 1122.279838   
2                                  771.616181   
3                                  741.035602   
4                                  308.633819   

   requester_days_since_first_post_on_raop_at_request  \
0                                           0.000000    
1                                           0.000000    
2                                           0.000000    
3                                           0.000000    
4                                         101.606505    

   requester_days_since_first_post_on_raop_at_retrieval  \
0                                         792.420405      
1                                         621.127072      
2                                         771.616181      
3                                         734.517164      
4                                         248.177072      

   requester_number_of_comments_at_request  \
0                                        0   
1                                        0   
2                                        0   
3                                       36   
4                                      140   

                       ...                       \
0                      ...                        
1                      ...                        
2                      ...                        
3                      ...                        
4                      ...                        

   requester_number_of_posts_at_retrieval  \
0                                       1   
1                                      26   
2                                       1   
3                                       2   
4                                      16   

   requester_number_of_posts_on_raop_at_request  \
0                                             0   
1                                             0   
2                                             0   
3                                             0   
4                                             0   

   requester_number_of_p

In [9]:
text_columns = ["request_text","request_title","requester_subreddits_at_request"]

df_text = df[text_columns].copy()
df_text['concat'] = df_text.apply(lambda x: ' '.join([str(y) for y in x if not pd.isnull(y)]), axis=1)
df_text.drop(text_columns, inplace=True, axis=1)

df_num = df.drop(text_columns, axis=1)

y = df_num["requester_received_pizza"].astype(int)

In [10]:
df_num.drop("requester_received_pizza", inplace=True, axis=1)

In [11]:
df_num_mat = df_num.as_matrix(columns=None)

In [12]:
type(df_num_mat)

numpy.ndarray

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
text_matrix = vectorizer.fit_transform(np.asarray(df_text['concat']))
text_matrix

<4040x19956 sparse matrix of type '<type 'numpy.float64'>'
	with 322827 stored elements in Compressed Sparse Row format>

In [14]:
from scipy import sparse
df_num_mat_sp = sparse.coo_matrix(df_num_mat)
train = sparse.hstack([df_num_mat_sp,text_matrix])
train.shape

(4040, 19976)

In [15]:
from sklearn import model_selection
Xtrain,Xtest,Ytrain,Ytest = model_selection.train_test_split(train,y,test_size=0.25,random_state=1992)

In [16]:
from sklearn.svm import LinearSVC

clf = LinearSVC(penalty='l1', dual=False)
class_svm = clf.fit(Xtrain, Ytrain)

In [17]:
pred_train_svm = class_svm.predict(Xtrain)
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_train_svm))  
pred_test_svm = class_svm.predict(Xtest)
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_test_svm)) 

[0 1]
[0 1]


In [18]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_svm, y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_svm, y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.91      0.97      0.94      2294
    received-1       0.88      0.69      0.78       736

   avg / total       0.90      0.90      0.90      3030

                precision    recall  f1-score   support

not received-0       0.86      0.94      0.90       752
    received-1       0.76      0.54      0.63       258

   avg / total       0.83      0.84      0.83      1010



In [19]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytrain, pred_train_svm))
print(confusion_matrix(Ytest, pred_test_svm))

[[2224   70]
 [ 226  510]]
[[709  43]
 [119 139]]


In [20]:
from sklearn.svm import LinearSVC

clf = LinearSVC(penalty='l2')
class_svm = clf.fit(Xtrain, Ytrain)

In [21]:
pred_train_svm = class_svm.predict(Xtrain)
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_train_svm))  
pred_test_svm = class_svm.predict(Xtest)
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_test_svm)) 

[0 1]
[0 1]


In [22]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_svm, y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_svm, y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.80      0.60      0.68      2294
    received-1       0.29      0.52      0.38       736

   avg / total       0.67      0.58      0.61      3030

                precision    recall  f1-score   support

not received-0       0.80      0.60      0.68       752
    received-1       0.32      0.57      0.41       258

   avg / total       0.68      0.59      0.61      1010



In [23]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytrain, pred_train_svm))
print(confusion_matrix(Ytest, pred_test_svm))

[[1366  928]
 [ 352  384]]
[[448 304]
 [112 146]]


In [24]:
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier

clf_sgd = SGDClassifier(penalty='l1')
class_sgd = clf_sgd.fit(Xtrain, Ytrain)

In [25]:
pred_train_sgd = class_sgd.predict(Xtrain)

print(np.unique(pred_train_sgd))  
pred_test_sgd = class_sgd.predict(Xtest)

print(np.unique(pred_test_sgd)) 

[0 1]
[0 1]


In [26]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_sgd, 
                            y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_sgd, 
                            y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.74      0.90      0.81      2294
    received-1       0.06      0.02      0.03       736

   avg / total       0.57      0.69      0.62      3030

                precision    recall  f1-score   support

not received-0       0.73      0.92      0.81       752
    received-1       0.08      0.02      0.03       258

   avg / total       0.56      0.69      0.61      1010



In [27]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytrain, pred_train_sgd))
print(confusion_matrix(Ytest, pred_test_sgd))

[[2063  231]
 [ 722   14]]
[[691  61]
 [253   5]]


In [28]:
from sklearn.linear_model import SGDClassifier

clf_sgd = SGDClassifier(penalty='l2')
class_sgd = clf_sgd.fit(Xtrain, Ytrain)

In [29]:
pred_train_sgd = class_sgd.predict(Xtrain)
print(np.unique(pred_train_sgd))  
pred_test_sgd = class_sgd.predict(Xtest)
print(np.unique(pred_test_sgd)) 

[0 1]
[0 1]


In [30]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_sgd, y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_sgd, y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.72      0.71      0.72      2294
    received-1       0.15      0.16      0.15       736

   avg / total       0.58      0.57      0.58      3030

                precision    recall  f1-score   support

not received-0       0.71      0.72      0.71       752
    received-1       0.14      0.14      0.14       258

   avg / total       0.56      0.57      0.57      1010



In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytrain, pred_train_sgd))
print(confusion_matrix(Ytest, pred_test_sgd))

[[1625  669]
 [ 621  115]]
[[541 211]
 [223  35]]


In [32]:
from sklearn.linear_model import SGDClassifier

clf_sgd = SGDClassifier(penalty='elasticnet')
class_sgd = clf_sgd.fit(Xtrain, Ytrain)

In [33]:
pred_train_sgd = class_sgd.predict(Xtrain)

print(np.unique(pred_train_sgd))  
pred_test_sgd = class_sgd.predict(Xtest)

print(np.unique(pred_test_sgd)) 

[0 1]
[0 1]


In [34]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_sgd, y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_sgd, y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.76      1.00      0.86      2294
    received-1       0.17      0.00      0.00       736

   avg / total       0.61      0.76      0.65      3030

                precision    recall  f1-score   support

not received-0       0.74      1.00      0.85       752
    received-1       0.00      0.00      0.00       258

   avg / total       0.55      0.74      0.64      1010



In [35]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytrain, pred_train_sgd))
print(confusion_matrix(Ytest, pred_test_sgd))

[[2289    5]
 [ 735    1]]
[[751   1]
 [258   0]]


In [37]:
from sklearn.linear_model import SGDClassifier

clf_sgd = SGDClassifier(penalty='none')
class_sgd = clf_sgd.fit(Xtrain, Ytrain)

In [38]:
pred_train_sgd = class_sgd.predict(Xtrain)
print(np.unique(pred_train_sgd))  
pred_test_sgd = class_sgd.predict(Xtest)
print(np.unique(pred_test_sgd)) 

[0 1]
[0 1]


In [39]:
from sklearn.metrics import classification_report
target_names = ['not received-0', 'received-1']
print(classification_report(y_pred = pred_train_sgd, y_true=Ytrain, target_names=target_names))
print(classification_report(y_pred = pred_test_sgd, y_true=Ytest, target_names=target_names))

                precision    recall  f1-score   support

not received-0       0.75      0.86      0.80      2294
    received-1       0.22      0.13      0.16       736

   avg / total       0.62      0.68      0.65      3030

                precision    recall  f1-score   support

not received-0       0.75      0.87      0.80       752
    received-1       0.28      0.15      0.20       258

   avg / total       0.63      0.69      0.65      1010

